# Generated by Django 3.1.3 on 2021-01-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('desc', models.TextField(blank=True, default='', max_length=2500, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='Data publikacji')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('desc', models.TextField(blank=True, default='', max_length=20000, null=True)),
                ('user_email', models.CharField(blank=True, max_length=50, null=True)),
                ('sender', models.CharField(blank=True, max_length=30, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Wysłania')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Tytuł sekcji', max_length=30, null=True)),
                ('desc', models.TextField(blank=True, default='Opis', max_length=15000, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='Data publikacji')),
                ('link', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('link_name', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('image', models.FileField(upload_to='static/')),
            ],
        ),
    ]
