# Generated by Django 3.1.3 on 2021-01-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Texts',
        ),
    ]
