# Generated by Django 3.1.3 on 2021-01-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210112_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texts',
        ),
    ]
