# Generated by Django 3.1.3 on 2021-01-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/'),
        ),
    ]
